import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar structure for the robotics textbook
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Course Outline',
      items: ['course-outline/index'],
      link: {
        type: 'doc',
        id: 'course-outline/index',
      },
    },
    {
      type: 'category',
      label: 'Module 1: Physical AI Foundations',
      collapsed: false,
      items: [
        'module-1/index',
        'module-1/chapter-1/index',
        'module-1/chapter-2/index',
        'module-1/chapter-3/index',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Simulation Environments (Gazebo & Unity)',
      collapsed: false,
      items: [
        'module-2/index',
        'module-2/chapter-1/index',
        'module-2/chapter-2/index',
        'module-2/chapter-3/index',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: Isaac AI & Navigation',
      collapsed: false,
      items: [
        'module-3/index',
        'module-3/chapter-1/index',
        'module-3/chapter-2/index',
        'module-3/chapter-3/index',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: VLA Robotics & Capstone',
      collapsed: false,
      items: [
        'module-4/index',
        'module-4/chapter-1/index',
        'module-4/chapter-2/index',
        'module-4/chapter-3/index',
      ],
    },
    {
      type: 'category',
      label: 'Capstone Project',
      items: ['capstone-project/index'],
      link: {
        type: 'doc',
        id: 'capstone-project/index',
      },
    },
  ],
};

export default sidebars;
